kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: nacos-poc
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30848
        hostPort: 8848
        protocol: TCP
      - containerPort: 30948
        hostPort: 9848
        protocol: TCP
